version: '3.8'
services:

  backend:
    build: back
    container_name: "nestjs"
    privileged: true
    tty: true
    depends_on:
      - dynamodb-local

  frontend:
    build: front
    container_name: "react"
    privileged: true
    tty: true
    depends_on:
      - backend

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./db/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

