version: "3.7"

services:
  backend:
    build: ./back/
    container_name: "nestjs"
    privileged: true
    ports:
      - "3001:3001"
    tty: true

  frontend:
    build: ./front/
    container_name: "react"
    privileged: true
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - backend
