version: "3.8"
services:
  backend:
    build: back
    container_name: "nestjs"
    privileged: true
    tty: true

  frontend:
    build: front
    container_name: "react"
    privileged: true
    tty: true
    depends_on:
      - backend
